# Generated by Django 5.2.5 on 2025-08-19 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(help_text='사용자가 업로드한 원본 파일', upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='파일 업로드 시간')),
                ('user', models.ForeignKey(help_text='파일을 업로드한 사용자', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='페이지 번호')),
                ('translated_html', models.TextField(help_text='번역된 HTML 콘텐츠')),
                ('html_url', models.CharField(help_text='HTML 콘텐츠 URL', max_length=255)),
                ('uploaded_file', models.ForeignKey(help_text='원본 파일', on_delete=django.db.models.deletion.CASCADE, to='mybook.uploadedfile')),
            ],
        ),
    ]
