# Generated by Django 5.2.5 on 2025-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='인증 서버에서 제공받은 username', max_length=150, unique=True)),
                ('email', models.EmailField(help_text='인증 서버에서 제공받은 email', max_length=254, unique=True)),
                ('secret_key', models.CharField(help_text='인증 서버와의 통신에서 사용할 secret_key, 인증서버에서 제공함', max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_type', models.CharField(default='None', help_text='사용자의 서비스 요금제 유형', max_length=50)),
                ('is_paid_member', models.BooleanField(default=False, help_text='유료 회원 여부')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='유료 구독 만료일', null=True)),
                ('cancel_requrest', models.BooleanField(default=False)),
                ('pdf_download_count', models.IntegerField(default=0, help_text='PDF 다운로드 횟수 (무료 회원 제한용)')),
                ('total_uploaded_files', models.IntegerField(default=0, help_text='총 업로드 파일 수')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='마지막 활동 시간')),
            ],
        ),
    ]
