# Generated by Django 5.2.5 on 2025-08-21 06:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatedpage',
            name='data',
            field=models.JSONField(default="{[]}", help_text='weaver.page.v1 JSON 형식의 번역 데이터'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatedpage',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='번역에 걸린 시간 (ms)', null=True),
        ),
        migrations.AddField(
            model_name='translatedpage',
            name='lang',
            field=models.CharField(default='ko', help_text='번역된 언어', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatedpage',
            name='mode',
            field=models.CharField(choices=[('faithful', '정밀 모드'), ('readable', '가독 모드')], default='faithful', help_text='번역 모드', max_length=16),
        ),
        migrations.AddField(
            model_name='translatedpage',
            name='page_no',
            field=models.IntegerField(default=1, help_text='번역된 페이지 번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatedpage',
            name='status',
            field=models.CharField(choices=[('pending', '대기 중'), ('ready', '준비 완료'), ('failed', '실패')], default='pending', help_text='번역 상태', max_length=16),
        ),
        migrations.AddField(
            model_name='translatedpage',
            name='tokens_used',
            field=models.IntegerField(blank=True, help_text='번역에 사용된 토큰 수', null=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='업로드된 책의 제목', max_length=255)),
                ('original_file', models.FileField(help_text='사용자가 업로드한 원본 파일', upload_to='original/')),
                ('file_hash', models.CharField(db_index=True, help_text='파일 내용의 해시값 (중복 업로드 방지용)', max_length=64, unique=True)),
                ('page_count', models.IntegerField(default=0, help_text='원본 문서의 총 페이지 수')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', help_text='문서 전체 처리 상태', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='파일을 업로드한 사용자', on_delete=django.db.models.deletion.CASCADE, to='mybook.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='translatedpage',
            name='book',
            field=models.ForeignKey(default="", on_delete=django.db.models.deletion.CASCADE, related_name='translated_pages', to='mybook.book'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='translatedpage',
            unique_together={('book', 'page_no', 'lang', 'mode')},
        ),
        migrations.RemoveField(
            model_name='translatedpage',
            name='html_url',
        ),
        migrations.RemoveField(
            model_name='translatedpage',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='translatedpage',
            name='translated_html',
        ),
        migrations.RemoveField(
            model_name='translatedpage',
            name='uploaded_file',
        ),
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField(help_text='페이지 번호 (1부터 시작)')),
                ('width', models.FloatField(help_text='페이지 너비 (px)')),
                ('height', models.FloatField(help_text='페이지 높이 (px)')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='mybook.book')),
            ],
            options={
                'unique_together': {('book', 'page_no')},
            },
        ),
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField(help_text='이미지가 속한 페이지 번호')),
                ('ref', models.CharField(db_index=True, help_text='이미지 참조 ID (예: img_p1_1)', max_length=64)),
                ('path', models.CharField(help_text='서버에 저장된 이미지 파일 경로', max_length=512)),
                ('bbox', models.JSONField(help_text='페이지 내 이미지 위치 및 크기 [x, y, w, h]')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mybook.book')),
            ],
            options={
                'unique_together': {('book', 'ref')},
            },
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
