# Generated by Django 5.2.5 on 2025-08-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0003_translatedpage_created_at_translatedpage_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='gemini_file_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='gemini_file_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='gemini_file_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='gemini_file_uri',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='source_mime',
            field=models.CharField(default='application/pdf', max_length=64),
        ),
        migrations.AddField(
            model_name='book',
            name='source_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
