# Generated by Django 5.2.5 on 2025-08-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0004_book_gemini_file_expires_at_book_gemini_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, help_text='책의 장르', max_length=100, null=True),
        ),
    ]
