# Generated by Django 5.2.5 on 2025-08-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0005_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='glossary',
            field=models.TextField(blank=True, help_text='번역에 사용할 사용자 정의 용어집', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('pending', '업로드 처리 대기 중'), ('uploaded', '번역 대기 중'), ('processing', '번역 중'), ('completed', '완료'), ('failed', '실패')], default='pending', help_text='문서 전체 처리 상태', max_length=16),
        ),
    ]
