# Generated by Django 5.2.5 on 2025-09-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0006_book_glossary_alter_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='book',
            name='file_hash',
            field=models.CharField(db_index=True, help_text='파일 내용의 해시값 (중복 업로드 방지용)', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('file_hash', 'owner'), name='unique_file_hash_owner'),
        ),
    ]
