# Generated by Django 5.2.5 on 2025-09-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0007_alter_book_options_alter_book_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ocr_status',
            field=models.CharField(choices=[('unknown', '판별 안됨'), ('ocr', 'OCR 처리됨'), ('image', 'OCR 미처리 (스캔본)')], default='unknown', help_text='PDF가 OCR로 처리된 텍스트 기반인지, 이미지 기반인지', max_length=16),
        ),
        migrations.AddField(
            model_name='book',
            name='text_coverage',
            field=models.FloatField(blank=True, help_text='페이지 내 텍스트 커버리지 비율(0.0~1.0). OCR 여부 추정 근거', null=True),
        ),
    ]
