# Generated by Django 5.2.5 on 2025-09-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0008_book_ocr_status_book_text_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='inspection',
            field=models.JSONField(blank=True, help_text='pdf_inspector.inspect_pdf() 결과의 직렬화된 dict', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='median_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='processing_mode',
            field=models.CharField(blank=True, help_text='pdf_inspector가 권장하는 처리 모드 (born_digital | ai_layout | mixed)', max_length=32, null=True),
        ),
    ]
