# Generated by Django 5.2.5 on 2025-09-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0009_book_avg_score_book_inspection_book_median_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='xref',
            field=models.IntegerField(blank=True, db_index=True, help_text=' OCR처리된 PDF 내 이미지 객체의 xref 번호', null=True),
        ),
    ]
