# Generated by Django 5.2.5 on 2025-09-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0010_pageimage_xref'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='transform',
            field=models.JSONField(blank=True, help_text='PDF CTM matrix [a,b,c,d,e,f] for positioning/cropping', null=True),
        ),
    ]
