# Generated by Django 5.2.5 on 2025-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0011_pageimage_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='clip_bbox',
            field=models.JSONField(blank=True, help_text='페이지내 이미지가 crop되었을때 클리핑마스크 bbox', null=True),
        ),
    ]
