# Generated by Django 5.2.5 on 2025-09-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0012_pageimage_clip_bbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='img_h',
            field=models.IntegerField(blank=True, help_text='이미지 원본 높이', null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='img_w',
            field=models.IntegerField(blank=True, help_text='이미지 원본 너비', null=True),
        ),
    ]
