# Generated by Django 5.2.5 on 2025-09-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0013_pageimage_img_h_pageimage_img_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='meta',
            field=models.JSONField(blank=True, help_text='페이지 normalize 이후의 메타정보', null=True),
        ),
    ]
