# Generated by Django 5.2.5 on 2025-09-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0014_book_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='meta',
        ),
        migrations.AddField(
            model_name='bookpage',
            name='meta',
            field=models.JSONField(blank=True, help_text='페이지 normalize 이후의 메타정보', null=True),
        ),
    ]
