# Generated by Django 5.2.5 on 2025-09-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0015_remove_book_meta_bookpage_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='origin_h',
            field=models.IntegerField(blank=True, help_text='원본 이미지 높이', null=True),
        ),
        migrations.AddField(
            model_name='pageimage',
            name='origin_w',
            field=models.IntegerField(blank=True, help_text='원본 이미지 너비', null=True),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='img_h',
            field=models.IntegerField(blank=True, help_text='서버에 저장된 이미지 높이', null=True),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='img_w',
            field=models.IntegerField(blank=True, help_text='서버에 저장된 이미지 너비', null=True),
        ),
    ]
