# Generated by Django 5.2.5 on 2025-09-18 06:40

import mybook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0016_pageimage_origin_h_pageimage_origin_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='clip_path',
            field=models.CharField(blank=True, help_text='페이지내 이미지가 crop되었을때 클리핑마스크 경로', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_file',
            field=models.FileField(help_text='사용자가 업로드한 원본 파일', upload_to=mybook.models.book_upload_to),
        ),
    ]
