# Generated by Django 5.2.5 on 2025-09-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0017_pageimage_clip_path_alter_book_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='clip_path',
            field=models.CharField(blank=True, help_text='페이지내 이미지가 crop되었을때 클리핑마스크 경로', null=True),
        ),
    ]
