# Generated by Django 5.2.5 on 2025-09-29 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0018_alter_pageimage_clip_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatedpage',
            name='tokens_used',
        ),
        migrations.CreateModel(
            name='ApiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(help_text="API 요청의 종류 (e.g., 'translate_page', 'retranslate_page')", max_length=50)),
                ('model_name', models.CharField(help_text='사용된 LLM 모델 이름', max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0, help_text='요청에 사용된 프롬프트 토큰 수')),
                ('completion_tokens', models.IntegerField(default=0, help_text='응답으로 받은 생성 토큰 수')),
                ('total_tokens', models.IntegerField(default=0, help_text='사용한 총 토큰 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, help_text='관련된 책 (선택 사항)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to='mybook.book')),
                ('user', models.ForeignKey(blank=True, help_text='요청을 발생시킨 사용자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_usage_logs', to='mybook.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
