# Generated by Django 5.2.5 on 2025-09-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0019_remove_translatedpage_tokens_used_apiusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='thinking_tokens',
            field=models.IntegerField(default=0, help_text='모델의 내부 추론(CoT)에 사용된 토큰 수'),
        ),
    ]
