# Generated by Django 5.2.5 on 2025-09-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0020_apiusagelog_thinking_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagelog',
            name='cached_tokens',
            field=models.IntegerField(default=0, help_text='프롬프트에서 재사용된 캐시 토큰 수'),
        ),
    ]
