# Generated by Django 5.2.5 on 2025-09-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0021_apiusagelog_cached_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusagelog',
            name='cached_tokens',
            field=models.IntegerField(blank=True, default=0, help_text='프롬프트에서 재사용된 캐시 토큰 수', null=True),
        ),
    ]
