# Generated by Django 5.2.5 on 2025-09-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0022_alter_apiusagelog_cached_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusagelog',
            name='thinking_tokens',
            field=models.IntegerField(blank=True, default=0, help_text='모델의 내부 추론(CoT)에 사용된 토큰 수', null=True),
        ),
    ]
