# Generated by Django 5.2.5 on 2025-09-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0023_alter_apiusagelog_thinking_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='gemini_file_expires_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='gemini_file_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='gemini_file_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='gemini_file_uri',
        ),
    ]
