# Generated by Django 5.2.5 on 2025-09-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0024_remove_book_gemini_file_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusagelog',
            name='completion_tokens',
            field=models.IntegerField(blank=True, default=0, help_text='응답으로 받은 생성 토큰 수', null=True),
        ),
        migrations.AlterField(
            model_name='apiusagelog',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, default=0, help_text='요청에 사용된 프롬프트 토큰 수', null=True),
        ),
    ]
