# Generated by Django 5.2.5 on 2025-10-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0025_alter_apiusagelog_completion_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cancel_requrest',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cancel_requested',
            field=models.BooleanField(default=False, help_text='사용자가 구독 해지를 요청했는지 여부'),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='xref',
            field=models.IntegerField(blank=True, db_index=True, help_text='OCR처리된 PDF 내 이미지 객체의 xref 번호', null=True),
        ),
    ]
