# Generated by Django 5.2.5 on 2025-10-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0026_remove_userprofile_cancel_requrest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(default='Free', help_text='사용자의 서비스 요금제 유형', max_length=50),
        ),
    ]
