# Generated by Django 5.2.5 on 2025-10-29 03:20

import mybook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0027_alter_userprofile_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edit_manifest',
            field=models.JSONField(blank=True, help_text='PDF 편집 상태(삭제/재정렬)', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='edited_file',
            field=models.FileField(blank=True, help_text='편집 커밋 후 생성된 PDF', null=True, upload_to=mybook.models.book_upload_to),
        ),
        migrations.AddField(
            model_name='book',
            name='previews_ready',
            field=models.BooleanField(default=False, help_text='썸네일 생성 완료 여부'),
        ),
    ]
